name: UI Testing and Allure Report Deployment

on:
  push:
    branches: [ "Tharaka-v2" ]
  pull_request:
    branches: [ "Tharaka-v2" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ui-testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: playwright-automation

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'playwright-automation/yarn.lock'

      - name: Create Allure Results Directory
        run: |
          mkdir -p allure-results
          chmod -R 777 allure-results

      - name: Install dependencies
        run: |
          yarn install
          yarn add -D @playwright/test allure-playwright

      - name: Update Playwright Config
        run: |
          echo "
          import { defineConfig } from '@playwright/test';
          export default defineConfig({
            reporter: [['line'], ['allure-playwright']],
            use: {
              headless: true,
              viewport: { width: 1280, height: 720 },
              ignoreHTTPSErrors: true,
              screenshot: 'only-on-failure',
            },
          });" > playwright.config.ts

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum yarn test
        continue-on-error: true
        env:
          CI: true

      - name: Debug Allure Results
        if: always()
        run: |
          echo "Checking allure-results directory:"
          ls -la allure-results/

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-allure-results
          path: playwright-automation/allure-results
          retention-days: 30

  deploy-report:
    needs: ui-testing
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - uses: actions/checkout@v4

      - name: Install Allure CLI
        run: |
          curl -o allure-2.24.0.tgz -OLs https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz -C /tmp
          sudo ln -s /tmp/allure-2.24.0/bin/allure /usr/local/bin/allure

      - name: Download UI Results
        uses: actions/download-artifact@v3
        with:
          name: ui-allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean
          touch allure-report/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: always()

      - name: Print Test Status
        if: always()
        run: |
          echo "UI Testing completed"
          echo "Allure report should be available at: ${{ steps.deployment.outputs.page_url }}"
